//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailServiceFacade.LiveDepartureBoard {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/", ConfigurationName="LiveDepartureBoard.LDBServiceSoap")]
    public interface LDBServiceSoap {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://thalesgroup.com/RTTI/2008-02-20/ldb/types) of message GetDepartureBoardRequest does not match the default value (http://thalesgroup.com/RTTI/2008-02-20/ldb/)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2008-02-20/ldb/GetDepartureBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RailServiceFacade.LiveDepartureBoard.GetDepartureBoardResponse GetDepartureBoard(RailServiceFacade.LiveDepartureBoard.GetDepartureBoardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://thalesgroup.com/RTTI/2008-02-20/ldb/types) of message GetArrivalBoardRequest does not match the default value (http://thalesgroup.com/RTTI/2008-02-20/ldb/)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2008-02-20/ldb/GetArrivalBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RailServiceFacade.LiveDepartureBoard.GetArrivalBoardResponse GetArrivalBoard(RailServiceFacade.LiveDepartureBoard.GetArrivalBoardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://thalesgroup.com/RTTI/2008-02-20/ldb/types) of message GetArrivalDepartureBoardRequest does not match the default value (http://thalesgroup.com/RTTI/2008-02-20/ldb/)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2008-02-20/ldb/GetArrivalDepartureBoard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RailServiceFacade.LiveDepartureBoard.GetArrivalDepartureBoardResponse GetArrivalDepartureBoard(RailServiceFacade.LiveDepartureBoard.GetArrivalDepartureBoardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://thalesgroup.com/RTTI/2007-10-10/ldb/types) of message GetServiceDetailsRequest does not match the default value (http://thalesgroup.com/RTTI/2008-02-20/ldb/)
        [System.ServiceModel.OperationContractAttribute(Action="http://thalesgroup.com/RTTI/2008-02-20/ldb/GetServiceDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        RailServiceFacade.LiveDepartureBoard.GetServiceDetailsResponse GetServiceDetails(RailServiceFacade.LiveDepartureBoard.GetServiceDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/commontypes")]
    public enum FilterType {
        
        /// <remarks/>
        to,
        
        /// <remarks/>
        from,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types")]
    public partial class StationBoard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime generatedAtField;
        
        private string locationNameField;
        
        private string crsField;
        
        private string filterLocationNameField;
        
        private string filtercrsField;
        
        private FilterType filterTypeField;
        
        private NRCCMessage[] nrccMessagesField;
        
        private bool platformAvailableField;
        
        private bool areServicesAvailableField;
        
        private ServiceItem[] trainServicesField;
        
        private ServiceItem[] busServicesField;
        
        private ServiceItem[] ferryServicesField;
        
        public StationBoard() {
            this.filterTypeField = FilterType.to;
            this.platformAvailableField = false;
            this.areServicesAvailableField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime generatedAt {
            get {
                return this.generatedAtField;
            }
            set {
                this.generatedAtField = value;
                this.RaisePropertyChanged("generatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string filterLocationName {
            get {
                return this.filterLocationNameField;
            }
            set {
                this.filterLocationNameField = value;
                this.RaisePropertyChanged("filterLocationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string filtercrs {
            get {
                return this.filtercrsField;
            }
            set {
                this.filtercrsField = value;
                this.RaisePropertyChanged("filtercrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public FilterType filterType {
            get {
                return this.filterTypeField;
            }
            set {
                this.filterTypeField = value;
                this.RaisePropertyChanged("filterType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message")]
        public NRCCMessage[] nrccMessages {
            get {
                return this.nrccMessagesField;
            }
            set {
                this.nrccMessagesField = value;
                this.RaisePropertyChanged("nrccMessages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool platformAvailable {
            get {
                return this.platformAvailableField;
            }
            set {
                this.platformAvailableField = value;
                this.RaisePropertyChanged("platformAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool areServicesAvailable {
            get {
                return this.areServicesAvailableField;
            }
            set {
                this.areServicesAvailableField = value;
                this.RaisePropertyChanged("areServicesAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] trainServices {
            get {
                return this.trainServicesField;
            }
            set {
                this.trainServicesField = value;
                this.RaisePropertyChanged("trainServices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] busServices {
            get {
                return this.busServicesField;
            }
            set {
                this.busServicesField = value;
                this.RaisePropertyChanged("busServices");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("service")]
        public ServiceItem[] ferryServices {
            get {
                return this.ferryServicesField;
            }
            set {
                this.ferryServicesField = value;
                this.RaisePropertyChanged("ferryServices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types")]
    public partial class NRCCMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types")]
    public partial class CallingPoint : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationNameField;
        
        private string crsField;
        
        private string stField;
        
        private string etField;
        
        private string atField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string st {
            get {
                return this.stField;
            }
            set {
                this.stField = value;
                this.RaisePropertyChanged("st");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string et {
            get {
                return this.etField;
            }
            set {
                this.etField = value;
                this.RaisePropertyChanged("et");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string at {
            get {
                return this.atField;
            }
            set {
                this.atField = value;
                this.RaisePropertyChanged("at");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types")]
    public partial class ServiceDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime generatedAtField;
        
        private ServiceType serviceTypeField;
        
        private string locationNameField;
        
        private string crsField;
        
        private string operatorField;
        
        private string operatorCodeField;
        
        private bool isCancelledField;
        
        private string disruptionReasonField;
        
        private string overdueMessageField;
        
        private string platformField;
        
        private string staField;
        
        private string etaField;
        
        private string ataField;
        
        private string stdField;
        
        private string etdField;
        
        private string atdField;
        
        private CallingPoint[][] previousCallingPointsField;
        
        private CallingPoint[][] subsequentCallingPointsField;
        
        public ServiceDetails() {
            this.isCancelledField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime generatedAt {
            get {
                return this.generatedAtField;
            }
            set {
                this.generatedAtField = value;
                this.RaisePropertyChanged("generatedAt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ServiceType serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("operatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCancelled {
            get {
                return this.isCancelledField;
            }
            set {
                this.isCancelledField = value;
                this.RaisePropertyChanged("isCancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string disruptionReason {
            get {
                return this.disruptionReasonField;
            }
            set {
                this.disruptionReasonField = value;
                this.RaisePropertyChanged("disruptionReason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string overdueMessage {
            get {
                return this.overdueMessageField;
            }
            set {
                this.overdueMessageField = value;
                this.RaisePropertyChanged("overdueMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
                this.RaisePropertyChanged("platform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string sta {
            get {
                return this.staField;
            }
            set {
                this.staField = value;
                this.RaisePropertyChanged("sta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
                this.RaisePropertyChanged("eta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ata {
            get {
                return this.ataField;
            }
            set {
                this.ataField = value;
                this.RaisePropertyChanged("ata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string std {
            get {
                return this.stdField;
            }
            set {
                this.stdField = value;
                this.RaisePropertyChanged("std");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string etd {
            get {
                return this.etdField;
            }
            set {
                this.etdField = value;
                this.RaisePropertyChanged("etd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string atd {
            get {
                return this.atdField;
            }
            set {
                this.atdField = value;
                this.RaisePropertyChanged("atd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPointList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPoint", NestingLevel=1)]
        public CallingPoint[][] previousCallingPoints {
            get {
                return this.previousCallingPointsField;
            }
            set {
                this.previousCallingPointsField = value;
                this.RaisePropertyChanged("previousCallingPoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPointList")]
        [System.Xml.Serialization.XmlArrayItemAttribute("callingPoint", NestingLevel=1)]
        public CallingPoint[][] subsequentCallingPoints {
            get {
                return this.subsequentCallingPointsField;
            }
            set {
                this.subsequentCallingPointsField = value;
                this.RaisePropertyChanged("subsequentCallingPoints");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/commontypes")]
    public enum ServiceType {
        
        /// <remarks/>
        train,
        
        /// <remarks/>
        bus,
        
        /// <remarks/>
        ferry,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types")]
    public partial class ServiceLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationNameField;
        
        private string crsField;
        
        private string viaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string locationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
                this.RaisePropertyChanged("locationName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string crs {
            get {
                return this.crsField;
            }
            set {
                this.crsField = value;
                this.RaisePropertyChanged("crs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string via {
            get {
                return this.viaField;
            }
            set {
                this.viaField = value;
                this.RaisePropertyChanged("via");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.21006.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types")]
    public partial class ServiceItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceLocation[] originField;
        
        private ServiceLocation[] destinationField;
        
        private string staField;
        
        private string etaField;
        
        private string stdField;
        
        private string etdField;
        
        private string platformField;
        
        private string operatorField;
        
        private string operatorCodeField;
        
        private bool isCircularRouteField;
        
        private string serviceIDField;
        
        public ServiceItem() {
            this.isCircularRouteField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("location")]
        public ServiceLocation[] destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string sta {
            get {
                return this.staField;
            }
            set {
                this.staField = value;
                this.RaisePropertyChanged("sta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string eta {
            get {
                return this.etaField;
            }
            set {
                this.etaField = value;
                this.RaisePropertyChanged("eta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string std {
            get {
                return this.stdField;
            }
            set {
                this.stdField = value;
                this.RaisePropertyChanged("std");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string etd {
            get {
                return this.etdField;
            }
            set {
                this.etdField = value;
                this.RaisePropertyChanged("etd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string platform {
            get {
                return this.platformField;
            }
            set {
                this.platformField = value;
                this.RaisePropertyChanged("platform");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
                this.RaisePropertyChanged("operator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("operatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool isCircularRoute {
            get {
                return this.isCircularRouteField;
            }
            set {
                this.isCircularRouteField = value;
                this.RaisePropertyChanged("isCircularRoute");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
                this.RaisePropertyChanged("serviceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartureBoardRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", IsWrapped=true)]
    public partial class GetDepartureBoardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=0)]
        public ushort numRows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=1)]
        public string crs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=2)]
        public string filterCrs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=3)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public RailServiceFacade.LiveDepartureBoard.FilterType filterType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int timeOffset;
        
        public GetDepartureBoardRequest() {
        }
        
        public GetDepartureBoardRequest(ushort numRows, string crs, string filterCrs, RailServiceFacade.LiveDepartureBoard.FilterType filterType, int timeOffset) {
            this.numRows = numRows;
            this.crs = crs;
            this.filterCrs = filterCrs;
            this.filterType = filterType;
            this.timeOffset = timeOffset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartureBoardResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", IsWrapped=true)]
    public partial class GetDepartureBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", Order=0)]
        public RailServiceFacade.LiveDepartureBoard.StationBoard GetDepartureBoardResult;
        
        public GetDepartureBoardResponse() {
        }
        
        public GetDepartureBoardResponse(RailServiceFacade.LiveDepartureBoard.StationBoard GetDepartureBoardResult) {
            this.GetDepartureBoardResult = GetDepartureBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalBoardRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", IsWrapped=true)]
    public partial class GetArrivalBoardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=0)]
        public ushort numRows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=1)]
        public string crs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=2)]
        public string filterCrs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=3)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public RailServiceFacade.LiveDepartureBoard.FilterType filterType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int timeOffset;
        
        public GetArrivalBoardRequest() {
        }
        
        public GetArrivalBoardRequest(ushort numRows, string crs, string filterCrs, RailServiceFacade.LiveDepartureBoard.FilterType filterType, int timeOffset) {
            this.numRows = numRows;
            this.crs = crs;
            this.filterCrs = filterCrs;
            this.filterType = filterType;
            this.timeOffset = timeOffset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalBoardResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", IsWrapped=true)]
    public partial class GetArrivalBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", Order=0)]
        public RailServiceFacade.LiveDepartureBoard.StationBoard GetArrivalBoardResult;
        
        public GetArrivalBoardResponse() {
        }
        
        public GetArrivalBoardResponse(RailServiceFacade.LiveDepartureBoard.StationBoard GetArrivalBoardResult) {
            this.GetArrivalBoardResult = GetArrivalBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalDepartureBoardRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", IsWrapped=true)]
    public partial class GetArrivalDepartureBoardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=0)]
        public ushort numRows;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=1)]
        public string crs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=2)]
        public string filterCrs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=3)]
        [System.ComponentModel.DefaultValueAttribute(FilterType.to)]
        public RailServiceFacade.LiveDepartureBoard.FilterType filterType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2008-02-20/ldb/types", Order=4)]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int timeOffset;
        
        public GetArrivalDepartureBoardRequest() {
        }
        
        public GetArrivalDepartureBoardRequest(ushort numRows, string crs, string filterCrs, RailServiceFacade.LiveDepartureBoard.FilterType filterType, int timeOffset) {
            this.numRows = numRows;
            this.crs = crs;
            this.filterCrs = filterCrs;
            this.filterType = filterType;
            this.timeOffset = timeOffset;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetArrivalDepartureBoardResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", IsWrapped=true)]
    public partial class GetArrivalDepartureBoardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", Order=0)]
        public RailServiceFacade.LiveDepartureBoard.StationBoard GetArrivalDepartureBoardResult;
        
        public GetArrivalDepartureBoardResponse() {
        }
        
        public GetArrivalDepartureBoardResponse(RailServiceFacade.LiveDepartureBoard.StationBoard GetArrivalDepartureBoardResult) {
            this.GetArrivalDepartureBoardResult = GetArrivalDepartureBoardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDetailsRequest", WrapperNamespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", IsWrapped=true)]
    public partial class GetServiceDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", Order=0)]
        public string serviceID;
        
        public GetServiceDetailsRequest() {
        }
        
        public GetServiceDetailsRequest(string serviceID) {
            this.serviceID = serviceID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceDetailsResponse", WrapperNamespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", IsWrapped=true)]
    public partial class GetServiceDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://thalesgroup.com/RTTI/2007-10-10/ldb/types", Order=0)]
        public RailServiceFacade.LiveDepartureBoard.ServiceDetails GetServiceDetailsResult;
        
        public GetServiceDetailsResponse() {
        }
        
        public GetServiceDetailsResponse(RailServiceFacade.LiveDepartureBoard.ServiceDetails GetServiceDetailsResult) {
            this.GetServiceDetailsResult = GetServiceDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LDBServiceSoapChannel : RailServiceFacade.LiveDepartureBoard.LDBServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LDBServiceSoapClient : System.ServiceModel.ClientBase<RailServiceFacade.LiveDepartureBoard.LDBServiceSoap>, RailServiceFacade.LiveDepartureBoard.LDBServiceSoap {
        
        public LDBServiceSoapClient() {
        }
        
        public LDBServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LDBServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDBServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LDBServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RailServiceFacade.LiveDepartureBoard.GetDepartureBoardResponse RailServiceFacade.LiveDepartureBoard.LDBServiceSoap.GetDepartureBoard(RailServiceFacade.LiveDepartureBoard.GetDepartureBoardRequest request) {
            return base.Channel.GetDepartureBoard(request);
        }
        
        public RailServiceFacade.LiveDepartureBoard.StationBoard GetDepartureBoard(ushort numRows, string crs, string filterCrs, RailServiceFacade.LiveDepartureBoard.FilterType filterType, int timeOffset) {
            RailServiceFacade.LiveDepartureBoard.GetDepartureBoardRequest inValue = new RailServiceFacade.LiveDepartureBoard.GetDepartureBoardRequest();
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            RailServiceFacade.LiveDepartureBoard.GetDepartureBoardResponse retVal = ((RailServiceFacade.LiveDepartureBoard.LDBServiceSoap)(this)).GetDepartureBoard(inValue);
            return retVal.GetDepartureBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RailServiceFacade.LiveDepartureBoard.GetArrivalBoardResponse RailServiceFacade.LiveDepartureBoard.LDBServiceSoap.GetArrivalBoard(RailServiceFacade.LiveDepartureBoard.GetArrivalBoardRequest request) {
            return base.Channel.GetArrivalBoard(request);
        }
        
        public RailServiceFacade.LiveDepartureBoard.StationBoard GetArrivalBoard(ushort numRows, string crs, string filterCrs, RailServiceFacade.LiveDepartureBoard.FilterType filterType, int timeOffset) {
            RailServiceFacade.LiveDepartureBoard.GetArrivalBoardRequest inValue = new RailServiceFacade.LiveDepartureBoard.GetArrivalBoardRequest();
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            RailServiceFacade.LiveDepartureBoard.GetArrivalBoardResponse retVal = ((RailServiceFacade.LiveDepartureBoard.LDBServiceSoap)(this)).GetArrivalBoard(inValue);
            return retVal.GetArrivalBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RailServiceFacade.LiveDepartureBoard.GetArrivalDepartureBoardResponse RailServiceFacade.LiveDepartureBoard.LDBServiceSoap.GetArrivalDepartureBoard(RailServiceFacade.LiveDepartureBoard.GetArrivalDepartureBoardRequest request) {
            return base.Channel.GetArrivalDepartureBoard(request);
        }
        
        public RailServiceFacade.LiveDepartureBoard.StationBoard GetArrivalDepartureBoard(ushort numRows, string crs, string filterCrs, RailServiceFacade.LiveDepartureBoard.FilterType filterType, int timeOffset) {
            RailServiceFacade.LiveDepartureBoard.GetArrivalDepartureBoardRequest inValue = new RailServiceFacade.LiveDepartureBoard.GetArrivalDepartureBoardRequest();
            inValue.numRows = numRows;
            inValue.crs = crs;
            inValue.filterCrs = filterCrs;
            inValue.filterType = filterType;
            inValue.timeOffset = timeOffset;
            RailServiceFacade.LiveDepartureBoard.GetArrivalDepartureBoardResponse retVal = ((RailServiceFacade.LiveDepartureBoard.LDBServiceSoap)(this)).GetArrivalDepartureBoard(inValue);
            return retVal.GetArrivalDepartureBoardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RailServiceFacade.LiveDepartureBoard.GetServiceDetailsResponse RailServiceFacade.LiveDepartureBoard.LDBServiceSoap.GetServiceDetails(RailServiceFacade.LiveDepartureBoard.GetServiceDetailsRequest request) {
            return base.Channel.GetServiceDetails(request);
        }
        
        public RailServiceFacade.LiveDepartureBoard.ServiceDetails GetServiceDetails(string serviceID) {
            RailServiceFacade.LiveDepartureBoard.GetServiceDetailsRequest inValue = new RailServiceFacade.LiveDepartureBoard.GetServiceDetailsRequest();
            inValue.serviceID = serviceID;
            RailServiceFacade.LiveDepartureBoard.GetServiceDetailsResponse retVal = ((RailServiceFacade.LiveDepartureBoard.LDBServiceSoap)(this)).GetServiceDetails(inValue);
            return retVal.GetServiceDetailsResult;
        }
    }
}
